
// This file defines the data models for users in the application.
// It includes a primary `UserModel` and several nested classes (`UserLocation`,
// `CustomerDetails`, `TailorDetails`) to represent the complex structure of user data
// received from the backend API. These models provide a structured and type-safe way
// to work with user information throughout the app.

class UserModel {
  // --- Core User Properties ---
  final String id; // The unique ID for the user, generated by the database.
  final String name;
  final String email;
  final String role; // The user's role, typically "customer" or "tailor".
  final String phone;
  final bool isVerified; // A flag indicating if the user has verified their email/phone.
  final String status; // The status of the user's account (e.g., "ACTIVE", "PENDING_VERIFICATION").

  // --- Nested Data Models ---
  final UserLocation? location; // The geographical location, mainly for tailors.
  final CustomerDetails? customerDetails; // Details specific to a customer user.
  final TailorDetails? tailorDetails; // Details specific to a tailor user.

  // --- Timestamps ---
  final DateTime? createdAt; // The timestamp when the user account was created.

  // The main constructor for creating a `UserModel` instance.
  // It includes default values for `isVerified` and `status`.
  UserModel({
    required this.id,
    required this.name,
    required this.email,
    required this.role,
    required this.phone,
    this.isVerified = false,
    this.status = "ACTIVE",
    this.location,
    this.customerDetails,
    this.tailorDetails,
    this.createdAt,
  });

  /// A factory constructor that creates a `UserModel` instance from a JSON map.
  /// This is the primary way that user data from the API is converted into a usable Dart object.
  /// It provides default values for missing fields to prevent null errors.
  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['_id'] ?? json['id'] ?? '', // Handles MongoDB's `_id` field.
      name: json['name'] ?? '',
      email: json['email'] ?? '',
      role: json['role'] ?? 'customer', // Defaults to 'customer' if the role is not specified.
      phone: json['phone'] ?? '',
      isVerified: json['isVerified'] ?? false,
      status: json['status'] ?? 'ACTIVE',
      // Recursively call `fromJson` for nested JSON objects.
      location: json['location'] != null ? UserLocation.fromJson(json['location']) : null,
      customerDetails: json['customerDetails'] != null
          ? CustomerDetails.fromJson(json['customerDetails'])
          : null,
      tailorDetails: json['tailorDetails'] != null
          ? TailorDetails.fromJson(json['tailorDetails'])
          : null,
      // Safely parse the date string into a DateTime object.
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'])
          : null,
    );
  }

  /// Converts a `UserModel` instance into a JSON map.
  /// This is useful for sending user data back to the server in API requests.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'email': email,
      'role': role,
      'phone': phone,
      'isVerified': isVerified,
      'status': status,
      // Recursively call `toJson` for nested objects.
      'location': location?.toJson(),
      'customerDetails': customerDetails?.toJson(),
      'tailorDetails': tailorDetails?.toJson(),
      'createdAt': createdAt?.toIso8601String(), // Convert DateTime to a standard ISO 8601 string.
    };
  }
}

/// A data model representing a geographical location using GeoJSON format.
class UserLocation {
  final String type; // The GeoJSON type, typically "Point".
  final List<double> coordinates; // A list containing [longitude, latitude].

  UserLocation({this.type = "Point", required this.coordinates});

  /// Factory constructor to create a `UserLocation` object from a JSON map.
  factory UserLocation.fromJson(Map<String, dynamic> json) {
    return UserLocation(
      type: json['type'] ?? "Point",
      // Safely converts a list of dynamic numbers into a list of doubles.
      coordinates: List<double>.from(json['coordinates'].map((x) => x.toDouble())),
    );
  }

  /// Converts a `UserLocation` instance into a JSON map.
  Map<String, dynamic> toJson() => {"type": type, "coordinates": coordinates};
}

/// A data model representing details specific to a "customer" role.
class CustomerDetails {
  final String? address;
  final String? city;
  final String? state;
  final String? landmark;
  final String? pin; // Pin code.

  CustomerDetails({this.address, this.city, this.state, this.landmark, this.pin});

  /// Factory constructor to create a `CustomerDetails` object from a JSON map.
  factory CustomerDetails.fromJson(Map<String, dynamic> json) {
    return CustomerDetails(
      address: json['address'],
      city: json['city'],
      state: json['state'],
      landmark: json['landmark'],
      pin: json['pin'],
    );
  }

  /// Converts a `CustomerDetails` instance into a JSON map.
  Map<String, dynamic> toJson() => {'address': address, 'city': city, 'state': state, 'landmark': landmark, 'pin': pin};
}

/// A data model representing the extensive details specific to a "tailor" role.
class TailorDetails {
  final String? shopName;
  final String? tailorType; // e.g., "Gents", "Ladies", "Both"
  final int? experience; // Years of experience.
  final List<String>? specializations; // e.g., ["Shirts", "Pants"]
  final List<String>? workingDays; // e.g., ["Monday", "Tuesday"]
  final Map<String, dynamic>? workingHours; // e.g., {"open": "10:00", "close": "20:00"}
  final Map<String, dynamic>? pricing; // e.g., {"basePrice": 400}
  final bool homePickup; // Does the tailor offer home pickup service?
  final bool measurementVisit; // Does the tailor offer to visit for measurements?
  final String? address;
  final String? city;
  final String? state;
  final String? zipCode;
  final String? landmark;
  final double rating; // The tailor's average user rating.
  final bool isAvailable; // Is the tailor currently accepting new orders?
  final String? profilePictureUrl;
  final String? shopPictureUrl;
  final List<String>? workPhotos; // URLs of photos showcasing the tailor's work.

  TailorDetails({
    this.shopName,
    this.tailorType,
    this.experience,
    this.specializations,
    this.workingDays,
    this.workingHours,
    this.pricing,
    this.homePickup = false,
    this.measurementVisit = false,
    this.address,
    this.city,
    this.state,
    this.zipCode,
    this.landmark,
    this.rating = 4.5, // Default rating.
    this.isAvailable = true, // Default availability.
    this.profilePictureUrl,
    this.shopPictureUrl,
    this.workPhotos,
  });

  /// Factory constructor to create a `TailorDetails` object from a JSON map.
  factory TailorDetails.fromJson(Map<String, dynamic> json) {
    return TailorDetails(
      shopName: json['shopName'],
      tailorType: json['tailorType'],
      experience: json['experience'],
      specializations: json['specializations'] != null ? List<String>.from(json['specializations']) : null,
      workingDays: json['workingDays'] != null ? List<String>.from(json['workingDays']) : null,
      workingHours: json['workingHours'],
      pricing: json['pricing'],
      homePickup: json['homePickup'] ?? false,
      measurementVisit: json['measurementVisit'] ?? false,
      address: json['address'],
      city: json['city'],
      state: json['state'],
      zipCode: json['zipCode'],
      landmark: json['landmark'],
      rating: (json['rating'] ?? 4.5).toDouble(),
      isAvailable: json['isAvailable'] ?? true,
      profilePictureUrl: json['profilePictureUrl'],
      shopPictureUrl: json['shopPictureUrl'],
      workPhotos: json['workPhotos'] != null ? List<String>.from(json['workPhotos']) : null,
    );
  }

  /// Converts a `TailorDetails` instance into a JSON map.
  Map<String, dynamic> toJson() => {
    'shopName': shopName,
    'tailorType': tailorType,
    'experience': experience,
    'specializations': specializations,
    'workingDays': workingDays,
    'workingHours': workingHours,
    'pricing': pricing,
    'homePickup': homePickup,
    'measurementVisit': measurementVisit,
    'address': address,
    'city': city,
    'state': state,
    'zipCode': zipCode,
    'landmark': landmark,
    'rating': rating,
    'isAvailable': isAvailable,
    'profilePictureUrl': profilePictureUrl,
    'shopPictureUrl': shopPictureUrl,
    'workPhotos': workPhotos,
  };
}
